### ISSUE TITLE
operators

### ISSUE THREAD

**Issue by ZeinabMostafaElSamahy** [hossa95/AsuMathLabG07#24]
./  :: divide by element
.^ :: power each element 
.+ :: add by element
.* :: multiply each element

/ :: divide matrix
^ :: power matrix "multiply matrix by itself" 
'+' :: add matrix
'*' :: multiply matrix

**Comment by RawanMahmoud** [comment]
we support all main operators, the by elements operators still not supported.

**Comment by AhmedSI** [comment]
I think that main should call function with parameter shows that the operation is by element.and the operator in another  parameter.
