### ISSUE TITLE
division function problem

### ISSUE THREAD

**Issue by doaakamel** [hossa95/AsuMathLabG07#5]
the first determinant function used in division function uses recursion method to calculate determinant  which takes too much time  in case of large matrices as a mathematical  alternative   lu decomposition was used to calculate determinant unfortunately  the function used in phase one fails in some test  cases for unknown reasons so we need to fix it or find another way

**Comment by HossamEmam95** [comment]
I think we should retest the current code to see why it fails and fix it rather than finding a new one. i will work on retesting and u try to fine a new one.

**Comment by MOSTAFAALAAAHMED** [comment]
it had been fixed and i have tested it and it is already works
