### ISSUE TITLE
Task: File separation 

### ISSUE THREAD

**Issue by HossamEmam95** [hossa95/AsuMathLabG07#7]
we need to separate the code file into three files and create the make file

**Comment by husseinadell** [comment]
it can be done by 3 files: Matrix.cpp ,Matrix.h and main.cpp 
but there is a problem in the Matrix.h file and working on it

**Comment by AhmedSI** [comment]
I have separated and uploaded it into SeparatedFiles2 branch

**Comment by AhmedSI** [comment]
I have separated the code into three files (main.cpp.header.h,matrix.cpp)
